CREATE TABLE credit_card_details (
    id VARCHAR(36) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(20,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    payment_status VARCHAR(20) NOT NULL,
    error_message TEXT,
    error_code VARCHAR(50),
    transaction_id VARCHAR(100),
    customer_id VARCHAR(100),
    metadata TEXT,
    card_token VARCHAR(255) NOT NULL,
    last4_digits CHAR(4) NOT NULL,
    card_brand VARCHAR(50) NOT NULL,
    installments INT,
    authorization_code VARCHAR(50),
    nsu VARCHAR(50),
    capture_id VARCHAR(100),
    captured_amount DECIMAL(20,2),
    captured_at TIMESTAMP NULL,
    refunded_amount DECIMAL(20,2),
    refunded_at TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0,
    
    INDEX idx_cc_status (payment_status),
    INDEX idx_cc_customer (customer_id),
    INDEX idx_cc_transaction (transaction_id),
    INDEX idx_cc_created (created_at),
    INDEX idx_cc_card (card_brand, last4_digits),
    INDEX idx_cc_capture (capture_id),
    
    CONSTRAINT chk_installments CHECK (installments IS NULL OR (installments >= 1 AND installments <= 12)),
    CONSTRAINT chk_amount CHECK (amount > 0),
    CONSTRAINT chk_captured_amount CHECK (captured_amount IS NULL OR captured_amount <= amount),
    CONSTRAINT chk_refunded_amount CHECK (refunded_amount IS NULL OR refunded_amount <= amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
