server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/catalogDB
    username: postgres
    password: 180281
    pool:
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.webflux.micromerce: DEBUG
