spring:
  application:
    name: payment-service
  data:
    r2dbc:
      url: r2dbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      pool:
        initial-size: 5
        max-size: 20
        max-idle-time: 30m
    properties:
      connect-timeout: 10
      ssl: false
  sql:
    init:
      mode: always
      platform: mysql
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      payment: payment-events
    consumer:
      group-id: payment-local-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: changeme


management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.webflux.micromerce: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.r2dbc: DEBUG
  file:
    path: ./logs
    name: ./logs/payment-service.log
